# Generated by Django 3.0.7 on 2020-06-05 10:49

from django.db import migrations
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.Hobbies'),
        ),
    ]
