# Generated by Django 3.0.7 on 2020-06-05 10:52

from django.db import migrations
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_person_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hobbies',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view='myapp.views.hobbies_autocomplete', blank=True, force_lowercase=True, initial='eating, coding, gaming', null=True, on_delete=django.db.models.deletion.CASCADE, to='tagging.Hobbies'),
        ),
    ]
